import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, CalendarDays, Check, Clock3, Instagram, MapPin, Menu, MessageCircle, ShoppingBag, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import stretchImage from "@/assets/class-stretch.jpg";
import trainingImage from "@/assets/class-training.jpg";
import studioImage from "@/assets/rhythm-studio.jpg";

export const Route = createFileRoute("/classes")({
  head: () => ({ meta: [
    { title: "Pole & Movement Classes | Rhythm Studio" },
    { name: "description", content: "Explore Rhythm Studio's curated pole, aerial, flexibility, and private movement classes in Bengaluru." },
    { property: "og:title", content: "Pole & Movement Classes | Rhythm Studio" },
    { property: "og:description", content: "Find your form in our curated collection of pole, aerial, and contemporary movement sessions." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: ClassesPage,
});

type ClassItem = { name: string; type: string; label: string; description: string; price: string; instructor?: string; image: string; cta?: string };

const classItems: ClassItem[] = [
  { name: "Open Practice", type: "Self", label: "Structured syllabus", description: "Unstructured studio time to practice independently. Access all poles, mats and props. An instructor is always present for guidance and safety.", price: "₹999", instructor: "Priya Krishnan", image: stretchImage },
  { name: "Exotic Beginners", type: "Group", label: "Structured syllabus", description: "Your first step into exotic pole. No experience required — just openness. Learn floorwork, transitions and movement vocabulary in a warm, non-judgmental space.", price: "From ₹2,100", instructor: "Sana Mirza", image: trainingImage, cta: "View batches" },
  { name: "Private Pole Session", type: "Private", label: "Personalized flow", description: "A fully personalised 75-minute one-on-one pole session. Your instructor designs every class around your goals, skill level and progression.", price: "₹6,000/class", instructor: "Priya Krishnan", image: studioImage },
  { name: "Advanced Pole", type: "Group", label: "Structured syllabus", description: "For experienced polers ready to push limits. Advanced inverts, combos and flow sequences. Not recommended for beginners.", price: "From ₹2,100", instructor: "Priya Krishnan", image: trainingImage },
  { name: "Stretch and Condition", type: "Group", label: "Structured syllabus", description: "A targeted 75-minute class improving flexibility, core strength and body awareness. The perfect complement to any pole or aerial training.", price: "From ₹1,500", instructor: "Divya Menon", image: stretchImage },
  { name: "Aerial Hoop Beginners", type: "Aerial", label: "Structured syllabus", description: "Discover the Lyra. Build upper body strength, coordination and beautiful lines in this structured beginner aerial hoop class. Max 6 per class.", price: "₹1,800", image: studioImage },
  { name: "Pole Level 2", type: "Group", label: "Structured syllabus", description: "Build on your foundations with more complex combinations, inverts and transitions. Dynamic, challenging and deeply rewarding.", price: "From ₹2,100", instructor: "Priya Krishnan", image: stretchImage },
  { name: "Pole Foundations", type: "Group", label: "Structured syllabus", description: "The essential starting point. Learn spins, body locks, climbs and basic inverts in this structured 75-minute class. Safe, encouraging and totally addictive.", price: "From ₹2,100", instructor: "Priya Krishnan", image: trainingImage },
];

function BrandMark() {
  return <Link to="/" aria-label="Rhythm Studio home" className="grid size-12 shrink-0 place-items-center rounded-full bg-espresso text-primary-foreground md:size-14"><span className="font-display text-[10px] italic leading-none">R</span><span className="-mt-3 text-[6px] uppercase tracking-[0.2em]">Rhythm</span></Link>;
}

function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="fixed inset-x-0 top-0 z-50 border-t-[3px] border-gold border-b border-border/50 bg-background/90 backdrop-blur-xl">
    <div className="mx-auto grid h-[72px] max-w-[1240px] grid-cols-[auto_minmax(0,1fr)_auto] items-center px-5 md:px-10">
      <BrandMark />
      <nav className="ml-7 hidden items-center gap-7 md:flex"><Link to="/classes" className="border-b border-gold pb-1 text-[13px] text-gold">Classes</Link>{["Schedule","Pricing","Instructors","About"].map((x)=><Link key={x} to="/" hash={x.toLowerCase()} className="text-[13px] transition-colors hover:text-gold">{x}</Link>)}</nav>
      <div className="flex items-center gap-3"><button aria-label="View bookings" className="grid size-10 place-items-center transition-colors hover:text-gold"><ShoppingBag className="size-[18px]"/></button><Link to="/" hash="footer" className="hidden px-2 text-[13px] hover:text-gold md:block">Sign in</Link><Button className="hidden h-10 rounded-lg px-6 text-[11px] uppercase tracking-[.16em] md:inline-flex"><CalendarDays/> Book a Class</Button><Button variant="ghost" size="icon" className="md:hidden" aria-label={open?"Close menu":"Open menu"} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>
    </div>
    {open&&<nav className="border-t border-border bg-background px-6 py-5 md:hidden"><Link to="/classes" className="block border-b border-border py-4 font-display text-2xl text-gold">Classes</Link>{["Schedule","Pricing","Instructors","About"].map(x=><Link onClick={()=>setOpen(false)} key={x} to="/" hash={x.toLowerCase()} className="block border-b border-border py-4 font-display text-2xl">{x}</Link>)}</nav>}
  </header>;
}

function BookingDialog({ item, close }: { item: ClassItem; close: () => void }) {
  const [confirmed,setConfirmed]=useState(false);
  return <div role="dialog" aria-modal="true" aria-labelledby="booking-title" className="fixed inset-0 z-[70] grid place-items-center bg-espresso/70 p-5 backdrop-blur-sm" onMouseDown={(e)=>{if(e.target===e.currentTarget)close()}}><div className="w-full max-w-lg rounded-xl border border-border bg-background p-6 shadow-2xl md:p-8"><div className="flex items-start justify-between"><div><p className="text-[9px] uppercase tracking-[.25em] text-gold">Reserve your place</p><h2 id="booking-title" className="mt-2 font-display text-3xl">{item.name}</h2></div><Button variant="ghost" size="icon" onClick={close} aria-label="Close booking"><X/></Button></div>{confirmed?<div className="py-12 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-gold-soft text-gold"><Check/></span><h3 className="mt-5 font-display text-2xl">Request received</h3><p className="mt-2 text-sm text-muted-foreground">The studio will contact you to confirm your session.</p><Button className="mt-6" onClick={close}>Done</Button></div>:<form className="mt-7 grid gap-4" onSubmit={(e)=>{e.preventDefault();setConfirmed(true)}}><label className="grid gap-2 text-xs font-medium">Your name<input required className="h-11 rounded-md border border-input bg-card px-3 outline-none focus:ring-2 focus:ring-ring" placeholder="Full name"/></label><label className="grid gap-2 text-xs font-medium">Phone number<input required type="tel" className="h-11 rounded-md border border-input bg-card px-3 outline-none focus:ring-2 focus:ring-ring" placeholder="+91 98765 43210"/></label><label className="grid gap-2 text-xs font-medium">Preferred session<select className="h-11 rounded-md border border-input bg-card px-3 outline-none focus:ring-2 focus:ring-ring"><option>Saturday · 10:00 AM</option><option>Sunday · 4:00 PM</option><option>Tuesday · 7:30 PM</option></select></label><div className="mt-2 flex items-center justify-between border-t border-border pt-5"><span className="font-display text-xl">{item.price}</span><Button type="submit">Request booking <ArrowRight/></Button></div></form>}</div></div>;
}

function ClassRow({ item, index, book }: { item: ClassItem; index: number; book: (item: ClassItem) => void }) {
  const reverse=index%2===1;
  return <article className="grid items-center gap-9 border-b border-border py-12 first:pt-0 md:gap-16 md:py-20 lg:grid-cols-2">
    <div className={`group relative overflow-hidden rounded-[4px_4px_32px_4px] shadow-xl ${reverse?'lg:order-2':''}`}><img src={item.image} alt={`${item.name} at Rhythm Studio`} width={1536} height={1024} loading={index===0?"eager":"lazy"} className="aspect-[1.78] w-full object-cover transition-transform duration-700 group-hover:scale-[1.035]"/><span className="absolute left-4 top-4 rounded-md bg-espresso px-4 py-2 text-[9px] font-semibold uppercase tracking-[.2em] text-primary-foreground">{item.type}</span></div>
    <div className={reverse?'lg:order-1':''}><div className="flex items-center gap-5"><span className="font-display text-xl text-gold">{String(index+1).padStart(2,'0')}</span><span className="h-px w-10 bg-border"/><span className="text-[9px] font-semibold uppercase tracking-[.28em] text-muted-foreground">{item.label}</span></div><h2 className="mt-7 font-display text-3xl md:text-[38px]">{item.name}</h2><p className="mt-5 max-w-lg text-sm leading-7 text-muted-foreground">{item.description}</p><div className="mt-6 grid max-w-md grid-cols-2 border-y border-dashed border-border py-4"><div><span className="block text-[8px] uppercase tracking-[.16em] text-muted-foreground">Session fee</span><strong className="mt-1 block text-xs">{item.price}</strong></div>{item.instructor&&<div className="border-l border-border pl-6"><span className="block text-[8px] uppercase tracking-[.16em] text-muted-foreground">Lead instructor</span><strong className="mt-1 flex items-center gap-2 text-xs"><i className="size-1 rounded-full bg-gold"/>{item.instructor}</strong></div>}</div><Button onClick={()=>book(item)} className="mt-7 h-11 px-7 text-[9px] uppercase tracking-[.2em]">{item.cta??"Book session"}<ArrowRight/></Button></div>
  </article>;
}

function SiteFooter() {
  return <footer className="bg-espresso py-16 text-primary-foreground"><div className="mx-auto max-w-[1200px] px-5 md:px-10"><div className="grid gap-12 border-b border-gold/20 pb-14 md:grid-cols-2 lg:grid-cols-4"><div><BrandMark/><p className="mt-6 max-w-xs text-xs leading-6 text-primary-foreground/50">Step into Bengaluru's premier sanctuary for architectural movement, strength, and contemporary flow.</p><a href="#top" aria-label="Instagram" className="mt-5 grid size-9 place-items-center rounded-lg border border-gold/30 hover:text-gold"><Instagram className="size-4"/></a></div><div><h3 className="text-[9px] uppercase tracking-[.3em] text-gold">Explore</h3><nav className="mt-6 space-y-3 text-xs text-primary-foreground/65"><Link to="/classes" className="block text-gold">Classes</Link>{["Schedule","Pricing","Instructors","About Us","Studio Policy","Contact Us"].map(x=><Link key={x} to="/" className="block hover:text-gold">{x}</Link>)}</nav></div><div><h3 className="text-[9px] uppercase tracking-[.3em] text-gold">Hours & info</h3><div className="mt-6 space-y-5 text-xs"><p className="flex gap-3"><Clock3 className="size-4 text-gold"/><span><strong>Mon – Fri</strong><small className="block text-primary-foreground/45">7:00 AM – 9:00 PM</small><strong className="mt-2 block">Sat – Sun</strong><small className="text-primary-foreground/45">8:00 AM – 6:00 PM</small></span></p><p className="flex gap-3"><MapPin className="size-4 text-gold"/><span>Koramangala,<br/>Bengaluru 560095</span></p></div></div><div><h3 className="text-[9px] uppercase tracking-[.3em] text-gold">Find us</h3><div className="mt-6 flex h-32 items-center justify-center rounded-xl border border-gold/20 bg-primary-foreground/5 text-xs text-primary-foreground/50"><MapPin className="mr-2 size-4 text-gold"/>Koramangala, Bengaluru</div></div></div><div className="flex flex-wrap justify-between gap-4 pt-8 text-[10px] text-primary-foreground/35"><span>© 2026 Rhythm Studio. All rights reserved.</span><a href="#top" className="text-gold">Back to top ↑</a></div></div></footer>;
}

function ClassesPage() {
  const [booking,setBooking]=useState<ClassItem | null>(null);
  return <main id="top"><SiteHeader/><section className="relative overflow-hidden pb-20 pt-36 text-center md:pb-28 md:pt-44"><div className="pointer-events-none absolute inset-0 flex items-start justify-center pt-28 font-display text-[18vw] text-foreground/[.025]">ARTISTRY</div><div className="relative mx-auto max-w-2xl px-5"><p className="text-[10px] font-semibold uppercase tracking-[.4em] text-gold">— &nbsp; Curated collection</p><h1 className="mt-5 font-display text-[44px] leading-none sm:text-[58px]">Curated <em className="text-gold">Classes</em></h1><div className="mx-auto my-7 h-px w-14 bg-gold"/><p className="text-sm leading-7 text-muted-foreground md:text-base">A refined collection of pole fitness, aerial suspension, and contemporary choreography — where strength is sculpted, control is developed, and poise is embodied.</p></div></section><section className="pb-28"><div className="mx-auto max-w-[1080px] px-6">{classItems.map((item,index)=><ClassRow key={item.name} item={item} index={index} book={setBooking}/>)}</div></section><section className="px-5 pb-28"><blockquote className="mx-auto max-w-3xl rounded-[30px] border border-border bg-ivory-deep px-8 py-20 text-center"><span className="mx-auto grid size-8 place-items-center rounded-full bg-gold-soft text-gold">◎</span><p className="mx-auto mt-6 max-w-xl font-display text-2xl italic leading-relaxed">“Every discipline requires a foundational structure. Find your form within our curated sessions.”</p><div className="mx-auto mt-5 h-px w-12 bg-gold"/></blockquote></section><SiteFooter/><a href="#footer" aria-label="Chat with us" className="fixed bottom-6 right-6 z-40 grid size-14 place-items-center rounded-full border-[5px] border-gold/50 bg-espresso text-primary-foreground shadow-2xl transition-transform hover:scale-105"><MessageCircle className="size-6"/></a>{booking&&<BookingDialog item={booking} close={()=>setBooking(null)}/>}</main>;
}